openapi: 3.0.0
info:
  title: CRUD API
  version: 1.0.0
  description: API for CRUD operations

paths:
  /items:
    get:
      summary: Retrieve all items
      responses:
        '200':
          description: Successful response
        '404':
          description: Not found
        '500':
          description: Internal server error

    post:
      summary: Create a new item
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Successful response
        '500':
          description: Internal server error

  /items/{itemId}:
    get:
      summary: Retrieve a specific item
      parameters:
        - name: itemId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
        '404':
          description: Not found
        '500':
          description: Internal server error

    put:
      summary: Update a specific item
      parameters:
        - name: itemId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Successful response
        '404':
          description: Not found
        '500':
          description: Internal server error

    delete:
      summary: Delete a specific item
      parameters:
        - name: itemId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
        '404':
          description: Not found
        '500':
          description: Internal server error

servers:
  - url: http://api.example.com/v1